// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: swipe_service.proto

package swipev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwipeService_Swipe_FullMethodName          = "/swipe.v1.SwipeService/Swipe"
	SwipeService_ListMatches_FullMethodName    = "/swipe.v1.SwipeService/ListMatches"
	SwipeService_UpdateLocation_FullMethodName = "/swipe.v1.SwipeService/UpdateLocation"
	SwipeService_GetCandidates_FullMethodName  = "/swipe.v1.SwipeService/GetCandidates"
)

// SwipeServiceClient is the client API for SwipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwipeServiceClient interface {
	// Swipe registers a like/dislike from swiper toward swipee.
	// If both users have liked each other a Match is created and returned.
	Swipe(ctx context.Context, in *SwipeRequest, opts ...grpc.CallOption) (*SwipeResponse, error)
	// ListMatches returns all matches of the caller.
	ListMatches(ctx context.Context, in *ListMatchesRequest, opts ...grpc.CallOption) (*ListMatchesResponse, error)
	// UpdateLocation stores the caller's coordinates in the geo index.
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	// GetCandidates returns nearby users within the service-configured radius.
	GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*GetCandidatesResponse, error)
}

type swipeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwipeServiceClient(cc grpc.ClientConnInterface) SwipeServiceClient {
	return &swipeServiceClient{cc}
}

func (c *swipeServiceClient) Swipe(ctx context.Context, in *SwipeRequest, opts ...grpc.CallOption) (*SwipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwipeResponse)
	err := c.cc.Invoke(ctx, SwipeService_Swipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swipeServiceClient) ListMatches(ctx context.Context, in *ListMatchesRequest, opts ...grpc.CallOption) (*ListMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMatchesResponse)
	err := c.cc.Invoke(ctx, SwipeService_ListMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swipeServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLocationResponse)
	err := c.cc.Invoke(ctx, SwipeService_UpdateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swipeServiceClient) GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*GetCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidatesResponse)
	err := c.cc.Invoke(ctx, SwipeService_GetCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwipeServiceServer is the server API for SwipeService service.
// All implementations must embed UnimplementedSwipeServiceServer
// for forward compatibility.
type SwipeServiceServer interface {
	// Swipe registers a like/dislike from swiper toward swipee.
	// If both users have liked each other a Match is created and returned.
	Swipe(context.Context, *SwipeRequest) (*SwipeResponse, error)
	// ListMatches returns all matches of the caller.
	ListMatches(context.Context, *ListMatchesRequest) (*ListMatchesResponse, error)
	// UpdateLocation stores the caller's coordinates in the geo index.
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	// GetCandidates returns nearby users within the service-configured radius.
	GetCandidates(context.Context, *GetCandidatesRequest) (*GetCandidatesResponse, error)
	mustEmbedUnimplementedSwipeServiceServer()
}

// UnimplementedSwipeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwipeServiceServer struct{}

func (UnimplementedSwipeServiceServer) Swipe(context.Context, *SwipeRequest) (*SwipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Swipe not implemented")
}
func (UnimplementedSwipeServiceServer) ListMatches(context.Context, *ListMatchesRequest) (*ListMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMatches not implemented")
}
func (UnimplementedSwipeServiceServer) UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedSwipeServiceServer) GetCandidates(context.Context, *GetCandidatesRequest) (*GetCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidates not implemented")
}
func (UnimplementedSwipeServiceServer) mustEmbedUnimplementedSwipeServiceServer() {}
func (UnimplementedSwipeServiceServer) testEmbeddedByValue()                      {}

// UnsafeSwipeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwipeServiceServer will
// result in compilation errors.
type UnsafeSwipeServiceServer interface {
	mustEmbedUnimplementedSwipeServiceServer()
}

func RegisterSwipeServiceServer(s grpc.ServiceRegistrar, srv SwipeServiceServer) {
	// If the following call panics, it indicates UnimplementedSwipeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwipeService_ServiceDesc, srv)
}

func _SwipeService_Swipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwipeServiceServer).Swipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwipeService_Swipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwipeServiceServer).Swipe(ctx, req.(*SwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwipeService_ListMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwipeServiceServer).ListMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwipeService_ListMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwipeServiceServer).ListMatches(ctx, req.(*ListMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwipeService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwipeServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwipeService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwipeServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwipeService_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwipeServiceServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwipeService_GetCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwipeServiceServer).GetCandidates(ctx, req.(*GetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwipeService_ServiceDesc is the grpc.ServiceDesc for SwipeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwipeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swipe.v1.SwipeService",
	HandlerType: (*SwipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Swipe",
			Handler:    _SwipeService_Swipe_Handler,
		},
		{
			MethodName: "ListMatches",
			Handler:    _SwipeService_ListMatches_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _SwipeService_UpdateLocation_Handler,
		},
		{
			MethodName: "GetCandidates",
			Handler:    _SwipeService_GetCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swipe_service.proto",
}
