// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: swipe_service.proto

package swipev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_LIKE        Direction = 1
	Direction_DIRECTION_DISLIKE     Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_LIKE",
		2: "DIRECTION_DISLIKE",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_LIKE":        1,
		"DIRECTION_DISLIKE":     2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_swipe_service_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_swipe_service_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{0}
}

type Swipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SwiperId      string                 `protobuf:"bytes,2,opt,name=swiper_id,json=swiperId,proto3" json:"swiper_id,omitempty"`
	SwipeeId      string                 `protobuf:"bytes,3,opt,name=swipee_id,json=swipeeId,proto3" json:"swipee_id,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=swipe.v1.Direction" json:"direction,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swipe) Reset() {
	*x = Swipe{}
	mi := &file_swipe_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swipe) ProtoMessage() {}

func (x *Swipe) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swipe.ProtoReflect.Descriptor instead.
func (*Swipe) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{0}
}

func (x *Swipe) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Swipe) GetSwiperId() string {
	if x != nil {
		return x.SwiperId
	}
	return ""
}

func (x *Swipe) GetSwipeeId() string {
	if x != nil {
		return x.SwipeeId
	}
	return ""
}

func (x *Swipe) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *Swipe) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Match struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User1Id   string                 `protobuf:"bytes,2,opt,name=user1_id,json=user1Id,proto3" json:"user1_id,omitempty"`
	User2Id   string                 `protobuf:"bytes,3,opt,name=user2_id,json=user2Id,proto3" json:"user2_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Второй участник матча относительно запрашивающего пользователя (ListMatches / Swipe).
	PeerUserId    string `protobuf:"bytes,5,opt,name=peer_user_id,json=peerUserId,proto3" json:"peer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_swipe_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{1}
}

func (x *Match) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Match) GetUser1Id() string {
	if x != nil {
		return x.User1Id
	}
	return ""
}

func (x *Match) GetUser2Id() string {
	if x != nil {
		return x.User2Id
	}
	return ""
}

func (x *Match) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Match) GetPeerUserId() string {
	if x != nil {
		return x.PeerUserId
	}
	return ""
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_swipe_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Candidate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Candidate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Candidate) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type SwipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwiperId      string                 `protobuf:"bytes,1,opt,name=swiper_id,json=swiperId,proto3" json:"swiper_id,omitempty"`
	SwipeeId      string                 `protobuf:"bytes,2,opt,name=swipee_id,json=swipeeId,proto3" json:"swipee_id,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=swipe.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwipeRequest) Reset() {
	*x = SwipeRequest{}
	mi := &file_swipe_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeRequest) ProtoMessage() {}

func (x *SwipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeRequest.ProtoReflect.Descriptor instead.
func (*SwipeRequest) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{3}
}

func (x *SwipeRequest) GetSwiperId() string {
	if x != nil {
		return x.SwiperId
	}
	return ""
}

func (x *SwipeRequest) GetSwipeeId() string {
	if x != nil {
		return x.SwipeeId
	}
	return ""
}

func (x *SwipeRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type SwipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swipe         *Swipe                 `protobuf:"bytes,1,opt,name=swipe,proto3" json:"swipe,omitempty"`
	Match         *Match                 `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"` // optional — set only on mutual like
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwipeResponse) Reset() {
	*x = SwipeResponse{}
	mi := &file_swipe_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeResponse) ProtoMessage() {}

func (x *SwipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeResponse.ProtoReflect.Descriptor instead.
func (*SwipeResponse) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{4}
}

func (x *SwipeResponse) GetSwipe() *Swipe {
	if x != nil {
		return x.Swipe
	}
	return nil
}

func (x *SwipeResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type ListMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesRequest) Reset() {
	*x = ListMatchesRequest{}
	mi := &file_swipe_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesRequest) ProtoMessage() {}

func (x *ListMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesRequest) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMatchesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMatchesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMatchesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesResponse) Reset() {
	*x = ListMatchesResponse{}
	mi := &file_swipe_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesResponse) ProtoMessage() {}

func (x *ListMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesResponse) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ListMatchesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMatchesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_swipe_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_swipe_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{8}
}

type GetCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesRequest) Reset() {
	*x = GetCandidatesRequest{}
	mi := &file_swipe_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesRequest) ProtoMessage() {}

func (x *GetCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetCandidatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesResponse) Reset() {
	*x = GetCandidatesResponse{}
	mi := &file_swipe_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesResponse) ProtoMessage() {}

func (x *GetCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swipe_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GetCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_swipe_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_swipe_service_proto protoreflect.FileDescriptor

const file_swipe_service_proto_rawDesc = "" +
	"\n" +
	"\x13swipe_service.proto\x12\bswipe.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\x05Swipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tswiper_id\x18\x02 \x01(\tR\bswiperId\x12\x1b\n" +
	"\tswipee_id\x18\x03 \x01(\tR\bswipeeId\x121\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x13.swipe.v1.DirectionR\tdirection\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x01\n" +
	"\x05Match\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\buser1_id\x18\x02 \x01(\tR\auser1Id\x12\x19\n" +
	"\buser2_id\x18\x03 \x01(\tR\auser2Id\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\fpeer_user_id\x18\x05 \x01(\tR\n" +
	"peerUserId\"\x7f\n" +
	"\tCandidate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\"{\n" +
	"\fSwipeRequest\x12\x1b\n" +
	"\tswiper_id\x18\x01 \x01(\tR\bswiperId\x12\x1b\n" +
	"\tswipee_id\x18\x02 \x01(\tR\bswipeeId\x121\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x13.swipe.v1.DirectionR\tdirection\"]\n" +
	"\rSwipeResponse\x12%\n" +
	"\x05swipe\x18\x01 \x01(\v2\x0f.swipe.v1.SwipeR\x05swipe\x12%\n" +
	"\x05match\x18\x02 \x01(\v2\x0f.swipe.v1.MatchR\x05match\"[\n" +
	"\x12ListMatchesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"n\n" +
	"\x13ListMatchesResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.swipe.v1.MatchR\amatches\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"j\n" +
	"\x15UpdateLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\"\x18\n" +
	"\x16UpdateLocationResponse\"/\n" +
	"\x14GetCandidatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x15GetCandidatesResponse\x123\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x13.swipe.v1.CandidateR\n" +
	"candidates*Q\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDIRECTION_LIKE\x10\x01\x12\x15\n" +
	"\x11DIRECTION_DISLIKE\x10\x022\xbb\x02\n" +
	"\fSwipeService\x128\n" +
	"\x05Swipe\x12\x16.swipe.v1.SwipeRequest\x1a\x17.swipe.v1.SwipeResponse\x12J\n" +
	"\vListMatches\x12\x1c.swipe.v1.ListMatchesRequest\x1a\x1d.swipe.v1.ListMatchesResponse\x12S\n" +
	"\x0eUpdateLocation\x12\x1f.swipe.v1.UpdateLocationRequest\x1a .swipe.v1.UpdateLocationResponse\x12P\n" +
	"\rGetCandidates\x12\x1e.swipe.v1.GetCandidatesRequest\x1a\x1f.swipe.v1.GetCandidatesResponseB$Z\"swipe-mgz/pkg/api/swipe/v1;swipev1b\x06proto3"

var (
	file_swipe_service_proto_rawDescOnce sync.Once
	file_swipe_service_proto_rawDescData []byte
)

func file_swipe_service_proto_rawDescGZIP() []byte {
	file_swipe_service_proto_rawDescOnce.Do(func() {
		file_swipe_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swipe_service_proto_rawDesc), len(file_swipe_service_proto_rawDesc)))
	})
	return file_swipe_service_proto_rawDescData
}

var file_swipe_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swipe_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_swipe_service_proto_goTypes = []any{
	(Direction)(0),                 // 0: swipe.v1.Direction
	(*Swipe)(nil),                  // 1: swipe.v1.Swipe
	(*Match)(nil),                  // 2: swipe.v1.Match
	(*Candidate)(nil),              // 3: swipe.v1.Candidate
	(*SwipeRequest)(nil),           // 4: swipe.v1.SwipeRequest
	(*SwipeResponse)(nil),          // 5: swipe.v1.SwipeResponse
	(*ListMatchesRequest)(nil),     // 6: swipe.v1.ListMatchesRequest
	(*ListMatchesResponse)(nil),    // 7: swipe.v1.ListMatchesResponse
	(*UpdateLocationRequest)(nil),  // 8: swipe.v1.UpdateLocationRequest
	(*UpdateLocationResponse)(nil), // 9: swipe.v1.UpdateLocationResponse
	(*GetCandidatesRequest)(nil),   // 10: swipe.v1.GetCandidatesRequest
	(*GetCandidatesResponse)(nil),  // 11: swipe.v1.GetCandidatesResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_swipe_service_proto_depIdxs = []int32{
	0,  // 0: swipe.v1.Swipe.direction:type_name -> swipe.v1.Direction
	12, // 1: swipe.v1.Swipe.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: swipe.v1.Match.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: swipe.v1.SwipeRequest.direction:type_name -> swipe.v1.Direction
	1,  // 4: swipe.v1.SwipeResponse.swipe:type_name -> swipe.v1.Swipe
	2,  // 5: swipe.v1.SwipeResponse.match:type_name -> swipe.v1.Match
	2,  // 6: swipe.v1.ListMatchesResponse.matches:type_name -> swipe.v1.Match
	3,  // 7: swipe.v1.GetCandidatesResponse.candidates:type_name -> swipe.v1.Candidate
	4,  // 8: swipe.v1.SwipeService.Swipe:input_type -> swipe.v1.SwipeRequest
	6,  // 9: swipe.v1.SwipeService.ListMatches:input_type -> swipe.v1.ListMatchesRequest
	8,  // 10: swipe.v1.SwipeService.UpdateLocation:input_type -> swipe.v1.UpdateLocationRequest
	10, // 11: swipe.v1.SwipeService.GetCandidates:input_type -> swipe.v1.GetCandidatesRequest
	5,  // 12: swipe.v1.SwipeService.Swipe:output_type -> swipe.v1.SwipeResponse
	7,  // 13: swipe.v1.SwipeService.ListMatches:output_type -> swipe.v1.ListMatchesResponse
	9,  // 14: swipe.v1.SwipeService.UpdateLocation:output_type -> swipe.v1.UpdateLocationResponse
	11, // 15: swipe.v1.SwipeService.GetCandidates:output_type -> swipe.v1.GetCandidatesResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_swipe_service_proto_init() }
func file_swipe_service_proto_init() {
	if File_swipe_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swipe_service_proto_rawDesc), len(file_swipe_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swipe_service_proto_goTypes,
		DependencyIndexes: file_swipe_service_proto_depIdxs,
		EnumInfos:         file_swipe_service_proto_enumTypes,
		MessageInfos:      file_swipe_service_proto_msgTypes,
	}.Build()
	File_swipe_service_proto = out.File
	file_swipe_service_proto_goTypes = nil
	file_swipe_service_proto_depIdxs = nil
}
